/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_buenas_tardes;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author hdani
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public NewJInternalFrame(JDesktopPane panel) {
        initComponents();
        this.setSize(590, 600);
        panel.add(this);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foto = new rojerusan.RSFotoSquare();
        descrip = new RSMaterialComponent.RSTextFieldOne();
        prec = new RSMaterialComponent.RSTextFieldOne();
        tam = new RSMaterialComponent.RSTextFieldOne();
        rSButtonRound1 = new rojerusan.RSButtonRound();
        rSButtonRound2 = new rojerusan.RSButtonRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 221, 232));

        descrip.setPlaceholder("INGRESA NOMBRE");
        getContentPane().add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 400, -1));

        prec.setPlaceholder("INGRESA EL PRECIO");
        getContentPane().add(prec, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 400, -1));

        tam.setPlaceholder("INGRESA EL TAMAÑO");
        getContentPane().add(tam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 400, -1));

        rSButtonRound1.setBackground(new java.awt.Color(153, 153, 0));
        rSButtonRound1.setText("REGISTRAR");
        rSButtonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        rSButtonRound2.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonRound2.setText("SALIR");
        rSButtonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRound2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("TAMAÑO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("PRECIO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound2ActionPerformed
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound2ActionPerformed

    private void rSButtonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRound1ActionPerformed
        Conexion x=new Conexion();
        x.Insertar_menu(descrip.getText(), prec.getText(), tam.getText(), foto.getRutaImagen());
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonRound1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTextFieldOne descrip;
    private rojerusan.RSFotoSquare foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private RSMaterialComponent.RSTextFieldOne prec;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojerusan.RSButtonRound rSButtonRound2;
    private RSMaterialComponent.RSTextFieldOne tam;
    // End of variables declaration//GEN-END:variables
}
