/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria_buenas_tardes;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author hdani
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagen/pizza.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        rSCalendarModern1 = new newscomponents.RSCalendarModern();
        rSButtonShape2 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape3 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape4 = new RSMaterialComponent.RSButtonShape();
        rSButtonShape5 = new RSMaterialComponent.RSButtonShape();

        rSPopuMenu1.setComponentPopupMenu(rSPopuMenu1);

        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jMenuItem1.setText("SALIR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        rSPopuMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jDesktopPane1.setComponentPopupMenu(rSPopuMenu1);

        rSButtonShape2.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShape2.setText("EMPLEADOS");
        rSButtonShape2.setBackgroundHover(new java.awt.Color(102, 153, 0));
        rSButtonShape2.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N

        rSButtonShape3.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShape3.setText("VENTAS");
        rSButtonShape3.setBackgroundHover(new java.awt.Color(0, 102, 255));
        rSButtonShape3.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N

        rSButtonShape4.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShape4.setText("MENU");
        rSButtonShape4.setBackgroundHover(new java.awt.Color(255, 51, 51));
        rSButtonShape4.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N
        rSButtonShape4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShape4ActionPerformed(evt);
            }
        });

        rSButtonShape5.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonShape5.setText("CLIENTES");
        rSButtonShape5.setActionCommand("");
        rSButtonShape5.setBackgroundHover(new java.awt.Color(204, 204, 0));
        rSButtonShape5.setFont(new java.awt.Font("Roboto Bold", 1, 36)); // NOI18N

        jDesktopPane1.setLayer(rSCalendarModern1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rSButtonShape2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rSButtonShape3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rSButtonShape4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rSButtonShape5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonShape2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonShape3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonShape4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonShape5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(rSCalendarModern1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(rSButtonShape2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(rSButtonShape4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(rSButtonShape5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(rSButtonShape3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSCalendarModern1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShape4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShape4ActionPerformed
           MENU x=new MENU(jDesktopPane1);
           jDesktopPane1.add(x);
           x.setSize(735, 630);
           x.show();
// TODO add your handling code here:
    }//GEN-LAST:event_rSButtonShape4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private RSMaterialComponent.RSButtonShape rSButtonShape2;
    private RSMaterialComponent.RSButtonShape rSButtonShape3;
    private RSMaterialComponent.RSButtonShape rSButtonShape4;
    private RSMaterialComponent.RSButtonShape rSButtonShape5;
    private newscomponents.RSCalendarModern rSCalendarModern1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    // End of variables declaration//GEN-END:variables
}
